namespace: telegram-bots

deployment:
  name: kwbot
  image: ghcr.io/preparingforexams/kwbot:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: kwbot
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 300m
    memory: 300Mi
  updateStrategy: Recreate

secret:
  name: kwbot
  botToken: __TELEGRAM_TOKEN__
