name: Build/Publish docker image

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          raw_command: lint
      - uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          raw_command: lint --strict

  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/preparingforexams/kwbot:${GITHUB_SHA} .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/preparingforexams/kwbot:${GITHUB_SHA}

  deploy:
    name: "Publish to k8s"
    runs-on: ubuntu-latest
    needs: [lint, build_push_docker]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - run: sed -i -e "s/__TELEGRAM_TOKEN__/${{ secrets.BOT_TOKEN }}/g" values.yaml\
      - run: sed -i -e "s/__TAG__/${GITHUB_SHA}/g" values.yaml
      - name: install helm chart
        uses: BlindfoldedSurgery/github-action-helm@v0.3.0
        with:
          subcommand: upgrade
          ref: .
          release_name: kwbot
          namespace: telegram-bots
          atomic: true
          install: true
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
